#spring:
#  thymeleaf:
#    mode: HTML

camel:
  component:
    kafka:
      schema-registry-u-r-l: http://localhost:8081
      brokers: http://localhost:9092
      # producer config
      #      lazy-start-producer: true
      #      request-timeout-ms: 10000
      retries: 3


